openssh/map.jinja
=> added archlinux support to openssh map.jinja

openssh/files/sshd_config, pillar.example
Can you please merge this little patch?
=> add ed25519 host key type; add AuthenticationMethods option

openssh/files/sshd_config, pillar.example
This will add more options to set to secure openssh
- AllowUsers
- AllowGroups
- DenyUsers
- DenyGroups
=> Added AllowUsers,AllowGroups,DenyUsers,DenyGroups

pillar.example
=> added the missing ":" and delete the redundant lines

openssh/defaults.yaml, openssh/map.jinja
Added defaults.yaml and map.jinja similar to template-formula and salt-formula
=> Improve default lookup

openssh/config.sls, pillar.example
With this you can specify which keys should be absent on a system.
=> Add option to remove ssh_host_keys

openssh/config.sls, pillar.example
i would really like to see that feature added.
if any questions just ask
=> add options to give a key size to generate_key

openssh/auth.sls
=> Use iteritems() instead of items().

openssh/auth.sls
=> Replaced iteritems deprecated function with items

openssh/files/sshd_config, pillar.example
I'm using this formulas for configure my PCI DSS Infrastructure and manage the session idle time out is one of the requirement.
https://cisofy.com/compliance/pci-dss/pci-dss-8-1-8-session-idle-timeout/
Thank you
=> Implement Session idle time out

openssh/files/sshd_config, pillar.example
Needed these two authentication options to be set.
- MaxAuthTries
- MaxSessions
=> add more authentication options

README.rst
like it was already done in the pillar.example in this PR https://github.com/saltstack-formulas/openssh-formula/pull/36 to avoid confusions.
=> Fix mine function example in README.rst

openssh/files/sshd_config
Upstream opensshd does not support PAM
=> do not set UsePAM on OpenBSD

.gitignore, .kitchen.yml, test/integration/default/serverspec/openssl_server_spec.rb
Set up the basic framework for automated testing using test-kitchen
=> Add test-kitchen configuration

openssh/config.sls, pillar.example
I'll merge in two to three days if there are no concerns with my addition.
Alex
=> Opt-in to enforce RSA key length

.kitchen.yml, test/integration/default/serverspec/openssl_server_spec.rb
Add kitchen tests for default file groups for FreeBSD and OpenBSD (wheel group).
=> FreeBSD wheel group

openssh/files/sshd_config
Resolves merge conflicts between #94 and #95
=> Prioritized compound match 2

openssh/config.sls
- generate before running `check_mk` on `sshd_config`
- set permissions on private key
- cope with empty keys
=> Fixed key generation

openssh/map.jinja
@fj40crawler would you please test this PR on your machines?
=> CentOS 6: UsePrivilegeSeparation 'yes' (fixes #108)

openssh/files/sshd_config, pillar.example
Add key or list based pillar data for the following options:
- DenyUsers
- AllowUsers
- DenyGroups
- AllowGroups
Based on MACs and Ciphers macro already present.
=> improve allow_deny_users_groups

openssh/config.sls
We have the following situation:
- A global pillar that forces generation of keys
- A specific pillar that setup a specific key for a specific host
So this fails because the formula generates a new key instead of first checking if there is a specific key.
Probably not the best way to solve this, but was the more straightforward.
Let me know what do you think.
Thanks!
=> [FIX] When key is present override generating by any way

openssh/config.sls
The purpose of this pull request is to allow using the config.sls state exclusively to configure keys (RSA, DSA, etc...) without managing the `sshd_config` (see issue #130). 
This is a pretty simple change that adds conditional evaluation to the `require_ins` applied to the key management states to make the key management states a requisite of the `sshd_config` management state.
@aboe76 @alxwr -- are either of you free to review this?
=> Fix invalid require_in sshd_config for key states

openssh/config.sls, openssh/defaults.yaml
=> Config backup option

openssh/files/ssh_config
=> Fix fetching default ssh_config.

README.rst
Some clarifications and corrections.
=> Improved known_hosts section in README.rst

openssh/config.sls
- `openssh/map.jinja`  has merged variables from defaults and pillar.
- `openssh/map.jinja` init the blank dict for ssh_config & sshd_config, and it is workable for conditional judgment.
=> reuse ssh_config, sshd_config from openssh/map.jinja

kitchen.vagrant.yml
---
No.
Follows on from #171.
Introduce a pre-salted FreeBSD Vagrant box for local testing, using:
```bash
$ INSTANCE=freebsd-120-2019-2-py3 \
&& export KITCHEN_LOCAL_YAML=kitchen.vagrant.yml
$ bin/kitchen verify ${INSTANCE}
```
This Vagrant box has been kindly prepared (and provided) by @krionbsd.
=> ci(kitchen): add pre-salted `FreeBSD-12.0` box for local testing

openssh/config_ini.sls
---
No.
#162 can still happen under some circumstances
Add a requisite to ensure states are applied in the correct order
```yaml
include:
- openssh.config_ini
/usr/sbin/sshd -t:
cmd.run:
- onchanges:
- ini: sshd_config-with-ini
- require_in:
- service: openssh
```
=> Ensure the tab replacement happens before the edit

openssh/config_ini.sls
---
No.
#178 
Previous fix was invalid, but was not caught by tests.
Turns out the correct change was to fix the mistake in the existing requisite.
The module is called `ini_manage` but the state prefix is `ini`.
=> fix(config_ini): stop failing after the first application

openssh/config.sls, openssh/files/default/ssh_config, openssh/files/default/ssh_known_hosts, openssh/files/default/sshd_config, openssh/known_hosts.sls
---
No.
The OpenSSH formula can't be used with `salt-ssh` because `map.jinja` is imported from templates.
We pass the pillars via the template engine context, this avoid the need to load `map.jinja` from the templates themselves and reduce the number of `pillar.get` calls.
* openssh/config.sls (sshd_config): pass `sshd_config` in the context.
(ssh_config): pass `ssh_config` in the context.
* openssh/files/default/ssh_config: remove `map.jinja` import since it's now in the context.
* openssh/files/default/sshd_config: ditoo.
* openssh/known_hosts.sls: pass `known_hosts` in the context.
* openssh/files/default/ssh_known_hosts: use `known_hosts` from the context instead of calling `pillar.get` several times.
=> feat(templates): don't get openssh pillars in templates

.travis.yml, kitchen.yml, openssh/config.sls, openssh/known_hosts.sls, test/integration/default/controls/packages_spec.rb
---
No.
I update the travis and kitchen test matrix to latest `template-formula` standard and fix few things for compatibility:
- feat(ci): update travis and kitchen to latest formula standards
- fix(jinja): encode context as json for python2
- fix(inspec): the package name for Arch is openssh
=> feat(ci): update ci to latest standards

kitchen.yml, openssh/known_hosts.sls, openssh/osfamilymap.yaml, test/integration/default/controls/config_spec.rb
---
No.
We test the generation of `/etc/ssh/ssh_known_hosts`.
It's already included in `test/salt/pillar/default.sls`.
=> test(config_spec): verify the generation of /etc/ssh/ssh_known_hosts

docs/README.rst, kitchen.yml, openssh/_mapdata/_mapdata.jinja, openssh/_mapdata/init.sls, test/integration/default/controls/_mapdata_spec.rb, test/integration/default/files/mapdata/amazonlinux-1.yaml, test/integration/default/files/mapdata/amazonlinux-2.yaml, test/integration/default/files/mapdata/arch-base-latest.yaml, test/integration/default/files/mapdata/centos-6.yaml, test/integration/default/files/mapdata/centos-7.yaml, test/integration/default/files/mapdata/centos-8.yaml, test/integration/default/files/mapdata/debian-10.yaml, test/integration/default/files/mapdata/debian-9.yaml, test/integration/default/files/mapdata/fedora-31.yaml, test/integration/default/files/mapdata/fedora-32.yaml, test/integration/default/files/mapdata/opensuse-15.yaml, test/integration/default/files/mapdata/ubuntu-16.yaml, test/integration/default/files/mapdata/ubuntu-18.yaml, test/integration/default/files/mapdata/ubuntu-20.yaml, test/integration/default/inspec.yml, test/integration/share/README.md, test/integration/share/inspec.yml, test/integration/share/libraries/system.rb
---
No.
This PR permits to validate the values gathered by `map.jinja` by:
- adding an `openssh._mapdata` state, used only for the CI (and the developpers), to generate a `/tmp/salt_mapdata_dump.yaml` file
- calling that new state in kitchen
- validating the `/tmp/salt_mapdata_dump.yaml` file against a canonical source
N/A
```
✔  `map.jinja` YAML dump: should contain the lines
✔  File /tmp/salt_mapdata_dump.yaml is expected to exist
✔  File /tmp/salt_mapdata_dump.yaml content is expected to include "# yamllint disable rule:indentation rule:line-length\n# Debian-10\n---\nopenssh:\n  absent_dsa_keys:...td: 'no'\n  Subsystem: sftp /usr/lib/openssh/sftp-server\n  UsePAM: 'yes'\n  X11Forwarding: 'yes'\n"
```
=> Ci/validate map.jinja

kitchen.yml, test/integration/default/controls/_mapdata_spec.rb, test/integration/default/files/_mapdata/amazonlinux-1.yaml, test/integration/default/files/_mapdata/amazonlinux-2.yaml, test/integration/default/files/_mapdata/arch-base-latest.yaml, test/integration/default/files/_mapdata/centos-6.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml, test/integration/share/README.md, test/integration/share/inspec.yml, test/integration/share/libraries/system.rb
---
No.
Do not modify `_mapdata` content to match hostname and force the hostname in `kitchen.yml` instead.
=> test(inspec): use static hostname in mapdata

openssh/_mapdata/_mapdata.jinja, openssh/_mapdata/init.sls, test/integration/default/controls/_mapdata_spec.rb, test/integration/default/files/_mapdata/amazonlinux-1.yaml, test/integration/default/files/_mapdata/amazonlinux-2.yaml, test/integration/default/files/_mapdata/arch-base-latest.yaml, test/integration/default/files/_mapdata/centos-6.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/284
=> refactor(map): use top-level `values:` key in `map.jinja` dumps

.github/workflows/kitchen.vagrant.yml, .yamllint, docs/README.rst, kitchen.vagrant.yml, kitchen.yml, openssh/known_hosts.sls, openssh/parameters/os_family/OpenBSD.yaml, test/integration/default/controls/config_spec.rb, test/integration/default/files/_mapdata/freebsd-11.yaml, test/integration/default/files/_mapdata/freebsd-12.yaml, test/integration/default/files/_mapdata/openbsd-6.yaml, test/salt/pillar/default.sls
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/304
Introduce FreeBSD (11.4 & 12.2) and OpenBSD (6.8) `kitchen-vagrant`-based testing.  Adds a minor fix for `dig_pkg`, where that's already available by default for OpenBSD.
=> ci: enable Vagrant-based testing using GitHub Actions

openssh/files/default/sshd_config
---
No.
It's a tiny change to the eventual layout of the generated sshd_config. 
We needed to do this to make the config compatible with the SaltStack Comply checks (was complaining about the whitespace difference)
=> Remove special newline handling for authentication options
