openssh/auth.sls, pillar.example
This change fixes #21 
Now auth.sls is able to use the current format 
```
joe:    # user
- name: joe
present: True
source: salt://ssh_keys/joe.id_rsa.pub
```
or the new format where it's now possible to swap the user and name entry in the pillar
```
joe-desktop:
- user: joe
present: True
source: salt://ssh_keys/joe.desktop.id_rsa.pub
joe-notebook:
- user: joe
present: True
source: salt://ssh_keys/joe.notebook.id_rsa.pub
```
=> Refactor auth.sls to allow more keys for one user

pillar.example
This fixes #34, salt version 2015.5.x needs an extra argument
for shell routines.
=> Fix mine_function example in pillar.example

openssh/files/ssh_known_hosts
Use jinja comment formatting to prevent the vi syntax line from being included in the ssh_known_hosts file written, which incidentally also corrupts the first line in ssh_known_hosts
=> Stop messing up the first line in ssh_known_hosts

openssh/files/sshd_config, pillar.example
Allows to harden the `sshd_config` with three additional configuration options:
1. KeyExchangeAlgorithms
2. Ciphers
3. MACs
The default options in `openssh/files/sshd_config` reflect the options as supported by Debian Wheezy. They are commented out by default.
The `pillar.example` options choose safe defaults - with a warning to check `man sshd_config` first before setting them.
This allows to implement the stuff mentioned in #26.
=> adds support to harden sshd_config (KeyExchange, Ciphers, MACs)

openssh/map.jinja
=> Added default path for sftp Subsystem in FreeBSD

openssh/files/ssh_config
This gives us the ability to define system-wide definitions for specific Hosts, and their options.
For example, with this in pillar:
```
ssh_config:
...
Hosts:
my-git:
User: git
HostName: git.example.com
Port: 2222
```
This would add a section in `/etc/ssh/ssh_config`:
```
Host my-git
User git
HostName git.example.com
Port 2222
```
=> Add support for Host definitions in ssh_config

openssh/defaults.yaml, openssh/files/sshd_config, openssh/known_hosts.sls, openssh/map.jinja
This PR does the following:
-  Add a separate mapping for the sshd_config dict to map.jinja. Currently, map.jinja adds the sftp subsystem entry to openssh instead of sshd_config (see https://github.com/saltstack-formulas/openssh-formula/pull/57).
- FreeBSD fixes: 
1. Only install the 'dig' package if no existing dig command is found ([salt.modules.dig](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dig.html) uses the dig command line tool). Currently, known_hosts.sls will always install the bind-tools package. However, dig is also provided by the full bind packages, which conflict with bind-tools. Applying this state will therefore remove your dns server :(
2. Set root group to wheel on FreeBSD hosts. Perhaps it would be easier to fix this one by using the gid (=0) …
=> Add sshd_config to map.jinja, and only install dig package if dig command not found.

openssh/defaults.yaml
This set of options reflect the ssh_config options that are set by
default on Debian. The way this was set before has the potential to
break exisisting setups that rely on "normal" defaults, rather than the
rather biased ones that are now being shipped with this formula.
I'd be happy to drop even more, but have the feeling as if the set of 
defaults below reflects, at least, the standard configuration on Debian
systems.
It is, in particular, rather annoying that the IdentityFile is hardcoded to 
`id_rsa` by default as this breaks setups that use newer key types (e.g. 
ed25519) and relied on various key types of them being tried.
The formula should, if it insists on specifying all these options right away
at least stick to the standard OpenSSH default values, rather than the opinionated …
=> Drop overly biased ssh_config defaults

openssh/map.jinja
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
$ rpm -qf $(which ssh)
openssh-clients-6.6.1p1-25.el7_2.x86_64
=> Correct openssh-clients package name for Red Hat

openssh/known_hosts.sls
Currently there is a cmd.run state that is always run and always generates a change in the run report.
We can work around this by extending it and adding an unless requisite, like so:
```
include:
- openssh.known_hosts # "check for existing dig"
extend:
check for existing dig:
cmd.run:
- unless: which dig
```
Alternatively, since the state is only used in one place, we can convert it to an unless requisite for that state. This commit does that.
=> Convert dig exist check to unless req to remove spurious change in report

openssh/map.jinja
This change corrects the package name  of the package containing dig so the state can work on a fresh install of ArchLinux.
=> Update name of package containing dig on ArchLinux

openssh/files/sshd_config
sshd exits with error "address family must be specified before ListenAddress" if the config option AddressFamily is specified. AddressFamily option needs to be moved to top of sshd_config to fix the issue.
=> sshd won't start if AddressFamily option is specified

openssh/auth.sls
openssh.auth will produce invalid SLS definition if no sshd_config is in pillar or AuthorizedKeysFile option missing in pillar.sshd_config, because of a stripped new-line in jinja endif statement on line 43.
```
[CRITICAL] Rendering SLS 'base:openssh.auth' failed: mapping values are not allowed here; line 8
---
[...]
simon-ed25519-ssh-key:
ssh_auth.present:
- user: root
- source: salt://ssh_keys/simon.pub- require:    <======================
- service: ssh
```
=> openssh.auth will produce invalid SLS definition if sshd_config configs are missing

openssh/defaults.yaml, openssh/init.sls, pillar.example
Add ability to control SSH server service status (default: on)
Updates `pillar.example`
Fixes #78
=> Add ability to control SSH server service status (default: on)

openssh/files/sshd_config
The config option `PrintLastLog` is missing in FreeBSD 10.3. This patch disables the default setting `PrintLastLog yes`.
=> PrintLastLog missing in FreeBSD 10.3

openssh/config.sls, openssh/defaults.yaml, pillar.example
Add secure defaults in `pillar.example`:
- Set `SeverKeyBits` to `1024` (from `768`) ( fixes #47 )
- Set `X11Forwarding` to `no` (from `yes`)
- Set `PrintMotd` to `yes` (from `no`)
- Update `KexAlgorithms`, `Ciphers` and `MACs` examples to include secure configuration based on https://stribika.github.io/2015/01/04/secure-secure-shell.html
Some of these changes can be altered, so let me know what you think. I beliee this would result in providing more secure default `pillar.example` file.
=> Add secure defaults to pillar.example + secure sshd_config in defaults.yml #66

.kitchen.yml, openssh/config.sls, openssh/defaults.yaml, test/integration/default/serverspec/openssl_server_spec.rb
Permit customization of file owner and mode for `ssh_config` and `sshd_config`. I added this because the current default is 644, but CIS benchmarks recommend 600.
=> Add variables for file owner and mode

README.rst, openssh/auth_map.sls, pillar.example
Hi!
Just wrote `openssh.auth_map`.
It provides essentially the same functionality as `openssh.auth` but with a simplified Pillar syntax.
Plays nicely with [Pillarstack](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html)
Has anybody any suggestions or remarks? (If not, I'll merge in two to three days.)
Alex
=> openssh.auth_map

openssh/config.sls, openssh/defaults.yaml
I managed to lock myself out of two servers for the third time now. :-) (Aparently `HostKeyAlgorithms` is unknown to `OpenSSH_6.7p1 Debian-5+deb8u3`...)
In anticipation of funny configuration bugs and/or my stupdity this PR adds a test prior to the change of `sshd_config`.
1. Fill `sshd_config.saltstack-test` with the exact same content which `sshd_config` should later contain.
2. Test it! `sshd -t -f /path/to/sshd_config.saltstack-test`
3. Iff (if and only if) that command succeeded change the actual config.
=> Test config before applying it

openssh/files/sshd_config
The fix introduced in 678cc9066cb358b8a436341b4e31b796b4d82a4c
suppresses the PrintLastLog directive for FreeBSD 10.3.
SSH on FreeBSD 11.0 also does not support PrintLastLog, so this
change suppresses it for any version >= 10.3.
=> PrintLastLog missing in FreeBSD 11.0

openssh/files/sshd_config
OpenSSH's Match declarations are applied first-match-wins. However, we
can't safely define two Matches that might overlap unless we first sort
the keys, as Python (and Jinja) dicts don't guarantee the order of
dict keys,
We also won't scramble the match sequence every time the user adds,
removes or renames a match, and so we give the user clearer, more
concise diffs as when they apply changes.
Finally, we leave a comment on the Match line identifying where the
Match rule came from, to assist in troubleshooting.
=> Support Match prioritization

openssh/files/sshd_config, pillar.example
This is was introduced in 5.9, and is default in 6.1.
https://www.openssh.com/txt/release-5.9
https://www.openssh.com/txt/release-6.1
It will stick with us for some time although it is going to be deprecated in 7.5.
https://www.openssh.com/txt/release-7.5
=> UsePrivilegeSeparation 'sandbox'

openssh/banner.sls
Fixed rendering `openssh.banner` state with multiline `banner_string` defined in the pillar.
The pillar:
```sls
openssh:                                                             
banner_string: |                                                   
Welcome to {{ grains['id'] }}.                                   
This machine is managed using SaltStack.                         
Do NOT modify any system settings.                               
Changes will either get lost or interfere with the machine setup.
```
The rendering error fixed in this pull request:
```sls
salt-master:
Data failed to compile:
----------
Rendering SLS 'base:openssh.banner' failed: could not found expected ':'; line 13
---
[...]
- name: /etc/ssh/banner
- contents: |
Welcome to salt-master.
This machine is managed …
```
=> Fixed supporting multiline banner_string defined in the pillar.

openssh/files/ssh_known_hosts, pillar.example
- Added a macro `known_hosts_entry` and comments to increase clarity.
- Opt-in (via pillar): add hostnames to `/etc/ssh/ssh_known_hosts`
Grants a wish: #110 ;-)
@doubletwist13 does that solve your problem?
Tested on Ubuntu 16.04 and FreeBSD 10.3.
=> Hostnames in known hosts

openssh/files/sshd_config
This prevents a verbatim version being added to end of file that will
cause the parsing to fail.
=> Add ConfigBanner to processed_options when handled.

openssh/files/sshd_config, openssh/map.jinja, pillar.example
fixes #102 
tested on:
- FreeBSD 10.3
- Debian 8.9
- Ubuntu 14.04
=> drop default values (fixes #102)

openssh/auth_map.sls
iteritems is deprecated in pyhthon3 should use items()
=> fix iteritems for python3

README.rst, openssh/config_ini.sls
=> [openssh/config_ini] initial version of config_ini which uses ini state

README.rst, openssh/files/ssh_known_hosts, pillar.example
Hey there,
I've added some bits to get public host keys from `pillar[`openssh:known_hosts:static']`
into the minions `ssh_known_hosts` file. No reason to have everyone check the keys
for things like gitlab themselves, right?
Tested on Ubuntu trusty & xenial, CentOS 6(.9) & 7(.4) and FreeBSD 10.4 & 11.1.
Regards, Florian
=> Add host keys from pillar to `ssh_known_hosts`

pillar.example
The `ssh_config` state supports generating `Host` sections, but it is
buried in the source. By default, options are simply dumped in the
configuration file; without any `Host` directive.
This patch hints (and, actually, encourages) users to use `Host`
sections by updating the pillar example to use the `Hosts` directive
with the `*` pattern.
=> Hint at `Host` support for `ssh_config`

openssh/client.sls, openssh/init.sls, pillar.example
The aim of this pull request is to allow the user to specify a version for server and client installs that should be installed. The version for the client is set by `openssh.client_version`  and for server by `openssh.server_version`.
The version field will only be set if configured if it is defined in the pillar. Therefore the PR will not break existing setups.
=> Support package versions

test/integration/helpers/serverspec/Gemfile
This hacky PR attempts to keep serverspec running natively for the distributions where `busser-serverspec` hasn't been lost entirely; ie: (from suite: ubuntu-14
```
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
Fetching: busser-0.7.1.gem (100%)
Successfully installed thor-0.19.0
Successfully installed busser-0.7.1
2 gems installed
-----> Installing Busser plugin: busser-serverspec
/usr/lib/ruby/1.9.1/rubygems/installer.rb:390:in `ensure_required_ruby_version_met': rake requires Ruby version >= 2.0.0. (Gem::InstallError)
```
Currently the platforms this fixes tests for are:
- debian-85
- centos-72
More specifically the failure this addresses is:
```
-----> Installing Serverspec..
Fetching: diff-lcs-1.3.gem (100%)
Fetching: rspec-mocks-3.8.0.gem (100%)
Fetching: …
```
=> Resolve gem dependencies across "supported" environments

openssh/files/sshd_config, pillar.example
Based on #119.
Removed these deprecated options from `pillar.example`:
* KeyRegenerationInterval
* ServerKeyBits
* RSAAuthentication
* RhostsRSAAuthentication
=> pillar.example: removed deprecated options

openssh/files/ssh_config
Based on the work of @johnnybubonic in #145 . Thanks for this.
* properly render host options in `/etc/ssh/ssh_config`
* optimized whitespace in `/etc/ssh/ssh_config`
I DID NOT TEST THIS MYSELF, because I currently leave `/etc/ssh/ssh_config` as it is.
Would someone please test the changes against a configuration containing `ssh_config:Hosts`? (@johnnybubonic maybe?)
----
@johnnybubonic I did not include your change regarding `ConfigBanner`, because AFAIK this would prevent `ConfigBanner` from being rendered at all.
=> ssh_config: properly render host options

openssh/auth.sls
This change allows keys to be not only added, but also removed by providing a `source` file. This is supported by `ssh_auth.absent` since salt 2015.8.0. Hope I have not overlooked anything.
=> Allow removing keys based on source file.

_pillar/known_hosts_salt_ssh.sls
(which also happened to break Python 3 compatibility.)
Tested on FreeBSD 11.2 with Salt 2019.2.0 and Python 3.6.
=> Dropped leftover debugging output

openssh/auth.sls, openssh/auth_map.sls, openssh/config_ini.sls, openssh/files/ssh_config
Follow #160 to remove remaining duplicated 'pillar.get' calls to retrieve the sshd_config and ssh_config pillars.
*Purpose:*
* Do code cleanup.
* Not ignore `sshd_config` & `ssh_config` variables in customized *defaults.yaml*.
*Impacted Files:*
- config_ini.sls
- auth_map.sls
- auth.sls
- files/ssh_config
=> Remove duplicated 'pillar.get' calls to retrieve the sshd_config and ssh_config pillars

openssh/config_ini.sls
* Fix #162
* Check for any number of tabs after the keyword
* If found, replace them by a single space to match the `separator` used
in the `ini_options.present` state
---
Note, this comment outlines the whole problem: https://github.com/saltstack-formulas/openssh-formula/issues/162#issuecomment-497110278.
Tested `sshd_config` with all combinations successfully:
Situation | Outcome
---|---
Already using single space per line | Only `ini_options.present` state runs
Single tab per line | Replaced by single space
Multiple tabs per line | Replaced by single space
=> fix(`config_ini`): convert tabs to single space to prevent false +ves

test/integration/default/controls/config_spec.rb
---
No.
Before:
```ruby
↺  openssh package: should be installed
↺  The `package` resource is not supported on your OS yet.
×  openssh configuration: should match desired lines (2 failed)
✔  File /etc/ssh/sshd_config is expected to be file
✔  File /etc/ssh/sshd_config is expected to be owned by "root"
×  File /etc/ssh/sshd_config is expected to be grouped into "root"
expected `File /etc/ssh/sshd_config.grouped_into?("root")` to return true, got false
✔  File /etc/ssh/sshd_config mode is expected to cmp == "0644"
✔  File /etc/ssh/sshd_config content is expected to include "ChallengeResponseAuthentication no"
✔  File /etc/ssh/sshd_config content is expected to include "X11Forwarding yes"
✔  File /etc/ssh/sshd_config content is expected to include "PrintMotd no"
✔  File /etc/ssh/sshd_config …
```
=> test(inspec): fix `config_spec` tests on *BSD (`wheel` not `root`)

docs/README.rst, openssh/files/default/ssh_known_hosts, pillar.example, test/salt/pillar/default.sls
---
No.
Servers like `github.com` are hosted on multiple IP addresses. When the IP address is retrieved via DNS this leads to a flapping `/etc/ssh/ssh_known_hosts`. To prevent that fluctuation the Pillar `openssh:known_hosts:omit_ip_address` was introduced. It can either specify a list of hosts or `True`.
I updated `test/salt/pillar/default.sls`.
```
host:                                                                                              
----------                                                                                                            
ID: manage ssh_known_hosts file                                                                             
Function: file.managed …
```
=> feat(ssh_known_hosts): allow to omit IP addresses

test/integration/default/controls/packages_spec.rb
---
No.
https://www.freebsd.org/doc/handbook/openssh.html
> OpenSSH is maintained by the OpenBSD project and is installed by default in FreeBSD.
Also includes:
* Refactor `package_name` using `case` like other formulas
As-is.
As shown in Travis as well as:
```ruby
$ KITCHEN_LOCAL_YAML=kitchen.vagrant.yml bin/kitchen verify default-freebsd-120-2019-2-py3
-----> Starting Test Kitchen (v2.3.4)
-----> Verifying <default-freebsd-120-2019-2-py3>...
Detected alternative framework tests for `serverspec`
Loaded default 
Profile: openssh formula (default)
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222
✔  openssh service: should be running and enabled
✔  Service sshd is expected to be enabled
✔  Service sshd is expected to be running
↺  openssh package: should be installed
↺  Skipped …
```
=> test(packages_spec): prevent control for `bsd` family

openssh/files/default/ssh_known_hosts
---
No.
It apprears that the
`if not (omit_ip_address is sameas true or host in omit_ip_address)`
always returns `True` on older Jinja platforms:
- default-ubuntu-1604-3000-3-py2
- default-ubuntu-1604-2019-2-py3
- default-amazonlinux-1-2019-2-py2
Each part of the `or` conditional need to be surrounded by parenthesis.
Before:
```
[INFO    ] Executing state file.managed for [/etc/ssh/ssh_known_hosts]
[DEBUG   ] Returning file list from cache: age=7 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Returning file list from cache: age=7 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] In saltenv 'base', looking at rel_path 'openssh/files/default/ssh_known_hosts' to resolve 'salt://openssh/files/default/ssh_known_hosts' …
```
=> fix(jinja): omit_ip_address don't work on some platform

test/integration/default/controls/_mapdata_spec.rb
---
No.
#187
The use of `eq` instead of `include` premits to have a nice diff after the `expected/got` oneliners.
N/A
Here is the output I get when modifying a `_mapdata` reference file:
```
×  `map.jinja` YAML dump: should contain the lines (1 failed)
✔  File /tmp/salt_mapdata_dump.yaml is expected to exist
×  File /tmp/salt_mapdata_dump.yaml content is expected to eq "# yamllint disable rule:indentation rule:line-length\n# Debian-10\n---\nmap_jinja:\n  config_get_roo...td: 'no'\n  Subsystem: sftp /usr/lib/openssh/sftp-server\n  UsePAM: 'yes'\n  X11Forwarding: 'yes'\n"
expected: "# yamllint disable rule:indentation rule:line-length\n# Debian-10\n---\nmap_jinja:\n  config_get_roo...td: 'no'\n  Subsystem: sftp /usr/lib/openssh/sftp-server\n  UsePAM: 'yes'\n  X11Forwarding: 'yes'\n"
got: "# …
```
=> test(inspec): display proper diff when `_mapdata` mismatch

pillar.example, test/integration/default/files/_mapdata/amazonlinux-1.yaml, test/integration/default/files/_mapdata/amazonlinux-2.yaml, test/integration/default/files/_mapdata/arch-base-latest.yaml, test/integration/default/files/_mapdata/centos-6.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml, test/salt/pillar/default.sls
---
No.
#164
The debug output of test jobs don't show the use of TOFS as it should and the pillar.example show that `tofs` is under `mine_functions` instead of `openssh`.
Before:
```
sshd_config:
file.managed:
- name: /etc/ssh/sshd_config
- source: 
- salt://openssh/files/example.net/sshd_config
- salt://openssh/files/Debian/sshd_config
- salt://openssh/files/default/sshd_config
- template: jinja
```
After:
```
sshd_config:
file.managed:
- name: /etc/ssh/sshd_config
- source: 
- salt://openssh/files/example.net/alt_sshd_config
- salt://openssh/files/example.net/sshd_config
- salt://openssh/files/Debian/alt_sshd_config
- salt://openssh/files/Debian/sshd_config
- salt://openssh/files/default/alt_sshd_config
- salt://openssh/files/default/sshd_config
- template: jinja
```
=> fix(pillar): `tofs` must not be under `mine_functions`

CODEOWNERS, openssh/_mapdata/init.sls, test/integration/default/controls/_mapdata_spec.rb, test/integration/share/README.md, test/integration/share/inspec.yml, test/integration/share/libraries/system.rb
---
No.
UPDATE: Automated using https://github.com/myii/ssf-formula/pull/281
~https://github.com/saltstack-formulas/sudoers-formula/pull/69~
Discussion in Slack: https://freenode.logbot.info/saltstack-formulas/20200826#c4886021-c4887283.
* https://docs.chef.io/inspec/resources/yaml/
=> test(map): standardise `map.jinja` verification

docs/README.rst, docs/map.jinja.rst, openssh/libmapstack.jinja, openssh/libmatchers.jinja, openssh/map.jinja, openssh/parameters/defaults.yaml, openssh/parameters/map_jinja.yaml, test/integration/default/files/_mapdata/amazonlinux-1.yaml, test/integration/default/files/_mapdata/amazonlinux-2.yaml, test/integration/default/files/_mapdata/arch-base-latest.yaml, test/integration/default/files/_mapdata/centos-6.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
---
Yes.
BREAKING CHANGE: the configuration `map_jinja:sources` is only configurable with `salt://parameters/map_jinja.yaml` and `salt://{{ tplroot }}/parameters/map_jinja.yaml`
BREAKING CHANGE: the `map_jinja:config_get_roots` is replaced by compound like `map_jinja:sources`
BREAKING CHANGE: the two `map_jinja:sources` `config_get_lookup` and `config_get` are replaced by `C@<tplroot>:lookup` and `C@<tplroot>` sources
#186
The `config_get_lookup` and `config_get` sources lack flexibility.
It's not easy to query several pillars and/or grains keys with the actual system. And the query method is forced to `config.get` without being configurable by the user.
We define a mechanism to select `map.jinja` sources with similar notation as the salt targeting system.
Each source has a type:
- `Y` to …
=> feat(map): use targeting like syntax for configuration

openssh/libmatchers.jinja, openssh/libsaltcli.jinja
---
No.
Fixes #203
fix(libmatchers): python client API can use `config.get` options
Only `salt-ssh` can't use them actually.
* openssh/libsaltcli.jinja: detect non empty `opts['__cli']` as `api`.
* openssh/libmatchers.jinja: only `ssh` and `unknown` can't use
`config.get` options `merge` and `delimiter`.
I created
- a simple `salt://foo/test.sls`
``` sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata with context %}
do-nothing:
test.nop:
- name: {{ mapdata | yaml }}
```
- a single `salt://foo/parameters/defaults`
``` yaml
values:
foo: 'bar'
```
With the following `test-libsaltcli` script:
``` python
#!/usr/bin/python3
import logging
logging.basicConfig(level=logging.INFO,
handlers=[logging.StreamHandler()])
import salt.client
caller = …
```
=> fix(libmatchers): python client API can use `config.get` options
